name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move to directory
      run: cd MicroCAnalyses  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: | 
        cd MicroCAnalyses 
        dotnet restore
    - name: Build
      run: | 
        cd MicroCAnalyses
        dotnet build --configuration Release --no-restore
    - name: Test
      run: | 
        cd MicroCAnalyses
        dotnet test --no-restore --verbosity normal
